version: '3.8'

services:
  watermark-service:
    build: .
    container_name: watermark-fiiin
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
    # Uncomment the next lines if you have an existing docker network for n8n
    # networks:
    #   - n8n-network

# Uncomment if you have an existing network
# networks:
#   n8n-network:
#     external: true